### ISSUE TITLE
Create a docker image in docker hub?

### ISSUE THREAD

**Issue by sinchb** [no13bus/redispapa#1]
This is  a great project!!! If you can create a docker image , it will be nice :)

https://registry.hub.docker.com/

**Comment by no13bus** [comment]
Good suggestion.
I am not familiar with the docker. I just register the docker hub. In the later time, I wll add this feature to a new version.
By the way, if you are good at the docker and have time to do it,  you can fork this repo and pull a requests to me.

**Comment by sinchb** [comment]
OK!  I will have a try in the later time :)

**Comment by no13bus** [comment]
@sinchb  have added docker.
